services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    volumes:
      - ./FE:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./BE:/app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    stdin_open: true
    tty: true

  db:
    image: postgres:15-alpine
    container_name: kalsium-db
    restart: always
    environment:
      POSTGRES_USER: kalsium_user
      POSTGRES_PASSWORD: kalsium_password
      POSTGRES_DB: kalsium_db
    ports:
      - "5432:5432"
    volumes:
      - kalsium-db-data:/var/lib/postgresql/data

volumes:
  kalsium-db-data:
